# Generated by Django 5.1.5 on 2025-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('location_id', models.IntegerField()),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_code', models.CharField(blank=True, max_length=100, null=True)),
                ('card_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
